### ISSUE TITLE
catkin build error 

### ISSUE THREAD

**Issue by Wayne-xixi** [ethz-asl/mav_trajectory_generation#102]
catkin build error like below:
`By not providing "Findyaml_cpp_catkin.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "yaml_cpp_catkin", but CMake did not find one.

  Could not find a package configuration file provided by "yaml_cpp_catkin"
  with any of the following names:

    yaml_cpp_catkinConfig.cmake
    yaml_cpp_catkin-config.cmake

  Add the installation prefix of "yaml_cpp_catkin" to CMAKE_PREFIX_PATH or
  set "yaml_cpp_catkin_DIR" to a directory containing one of the above files.
  If "yaml_cpp_catkin" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:5 (catkin_simple)
` 
Anyone can help me ? Thanks!

**Comment by Wayne-xixi** [comment]
solved by git clone yaml_cpp_catkin

**Comment by kadhirumasankar** [comment]
For users running into this issue in the future, more detailed instructions on how to clone yaml_cpp_catkin are available in #106
