### ISSUE TITLE
Documentation neglects to mention certain installation dependencies

### ISSUE THREAD

**Issue by nightduck** [ethz-asl/mav_trajectory_generation#105]
When building according to the instructions, two issues pop up: missing cmake references to catkin_simple and yaml_cpp_catkin. There are existing issues (#79 and #102 ) that reference these problems, but both issues are closed with the simple solution to clone requisite repositories into the src directory of the catkin workspace.
However, this quintessential fix is not referenced anywhere in the Readme or the wiki. Anyone who installs this repo has to go down the same rabbithole of issue reports, and it would be convenient to mention in the Readme that you have to manually clone extra repositories. ([I have provided a patch to do that](https://github.com/ethz-asl/mav_trajectory_generation/files/4471930/documentation.txt))

Also convenient: have them pulled automatically, see PR #104

**Comment by rikba** [comment]
Should be resolved in https://github.com/ethz-asl/mav_trajectory_generation/pull/116
