### ISSUE TITLE
Segment Cost computation

### ISSUE THREAD

**Issue by jh-kandarp** [ethz-asl/mav_trajectory_generation#107]
Hello, 

Thank you for open open sourcing  your implementation. 

In polynomial_optimization_linear_impl, 
the segment cost is computed as 0.5 * c^T * Q * c

Can you please explain reason for multiplication factor of 0.5 ? 

Thanks

**Comment by rikba** [comment]
As far as I know this is just for convenience. If you compute the gradient you get a fixed scalar free expression, i.e., d/dc (0.5 * c^T * Q * c) = Q * c
