### ISSUE TITLE
omav reference angular acceleraion

### ISSUE THREAD

**Issue by weixuanzhang** [ethz-asl/mav_trajectory_generation#109]
@maxb91 It seems that the reference angular acceleration in SquadOptimization::addToStates is not computed correctly, as states->at(i - 1).angular_velocity_W is zero when computing the omega_dot.
See the code here:
https://github.com/ethz-asl/mav_trajectory_generation/blob/af221a3cd51e27aedb8897c3bba80a93c2a187aa/mav_trajectory_generation/include/mav_trajectory_generation/impl/squad_optimization_impl.h#L84-L86
I can update the code upon confirmation. Shouldn't be too hard.

**Comment by maxb91** [comment]
Nice catch! Fixed in 3bcdf63.

**Comment by maxb91** [comment]
Amended previous commit to set last reference angular velocity and acceleration to zero. Was leading to weird behavior otherwise if constant nonzero references were published after finishing a trajectory.
New commit: 14d430e2d8bd6d1e6e030d6b653b8808c6dbad6e
