### ISSUE TITLE
rviz crashes on drawMavTrajectory

### ISSUE THREAD

**Issue by marija-p** [ethz-asl/mav_trajectory_generation#13]
Hi,

I'm not sure if this repo is the correct place to put this issue, but I seem to be having some trouble using the function ``drawMavTrajectory`` with ROS Kinetic on Ubuntu 16.04.

Here's what happened:
I tried to run [waypoint_navigator](https://github.com/ethz-asl/mav_pathplanning/tree/master/waypoint_navigator) from [mav_pathplanning](https://github.com/ethz-asl/mav_pathplanning) as an example of using mav_trajectory generation. As per the README, the node should publish ``/waypoint_navigator_polynomial_markers`` (visualization_msgs/MarkerArray - rviz marker for polynomial paths) using the function ``drawMavTrajectory``. However, when I try displaying these markers in rviz, I get the following errors in the console, followed by a rviz crash:

```
[ INFO] [1492718927.355060126]: rviz version 1.12.4
[ INFO] [1492718927.355167276]: compiled against Qt version 5.5.1
[ INFO] [1492718927.355194424]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1492718927.986305039, 102.220000000]: Stereo is NOT SUPPORTED
[ INFO] [1492718927.986463253, 102.220000000]: OpenGl version: 3 (GLSL 1.3).
rviz: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreNode.cpp:630: virtual void Ogre::Node::setScale(const Ogre::Vector3&): Assertion `!inScale.isNaN() && "Invalid vector supplied as parameter"' failed.
Aborted (core dumped)
```

This might be a Kinetic/16.04 issue, because I remember the visualization tools worked fine on my old 14.04 machine. Has anyone experienced this before? Is there another example I could try for debugging? Any advice on how to proceed would be greatly appreciated!

**Comment by frontw** [comment]
Hi! Cool repo!
Could I ask, are waypoint_navigator and mav_pathplanning mentioned here public available?
Want to try mav_trajectory_generation with some GUI.
Thanks!

**Comment by marco-tranzatto** [comment]
@frontw open another issue for a different question please.

**Comment by rikba** [comment]
Hi @frontw ,

`waypoint_navigator` and `mav_pathplanning` are still closed source. But you can interface `mav_trajectory_generation` writing your own node that receives waypoints over messages or loads them from a parameter file and then generates trajectories. You can then display the trajectories using the visualization tools in `mav_trajectory_generation`. Good luck :)
