### ISSUE TITLE
how to use it with octomap

### ISSUE THREAD

**Issue by Annaiyan** [ethz-asl/mav_trajectory_generation#28]
Hi,
I have recorded stereo data in rosbag. using which i can create a octomap and now i want to test this mav_trajectory_generation node. 
what are all the topics needs to subscribed from the octomap to generate the smooth trajectory?
thanks!

--arun

**Comment by rikba** [comment]
Hi Arun,

this package only lets you generate smooth polynomial segments between a list of waypoints. For a collision free path within an octomap a few extra steps are necessary.

[Richter, Bry and Roy](https://pdfs.semanticscholar.org/2376/078d13761387cabb933798b93a706c2ea7ef.pdf) suggest finding a straight-line RRT* plan first (e.g. using [OMPL](http://ompl.kavrakilab.org/)) and then connecting the waypoints of this plan with minimum-snap polynomials. See the paper for details.

Best,
Rik
