### ISSUE TITLE
Compilation under Mac OS

### ISSUE THREAD

**Issue by GigaFlopsis** [ethz-asl/mav_trajectory_generation#45]
Hello. Were you able to compile the library under Mac OS
The fact that the function

```
// srs/vectex.cpp  162 line
std::vector<double> estimateSegmentTimes(const Vertex::Vector& vertices,
                                         double v_max, double a_max,
                                         double magic_fabian_constant = 6.5);

```
return NAN.

If you have experienced this, tell me how to solve this problem?

Best regards,
Devitt Dmitry

**Comment by helenol** [comment]
Is this closed because this is resolved? I run everything on OS X and haven't had this issue.

**Comment by GigaFlopsis** [comment]
Hello Helen. I solve problem. The problem was in the mac os compiler. He
can not increment very small numbers to zero (for example 6.574-302 != 0)

Regards,
Dmitry Devitt

4 окт. 2017 г. 1:46 ПП пользователь "Helen Oleynikova" <
notifications@github.com> написал:
