### ISSUE TITLE
catkin build fails for glog_catkin

### ISSUE THREAD

**Issue by m1baldwin** [ethz-asl/mav_trajectory_generation#66]
I have tried to follow the installation and build instructions, however it would seem that the build process fails at the following step:

Workspace configuration appears valid.
-----------------------------------------------------------
[build] Found '8' packages in 0.0 seconds.                                     
[build] Package table is up to date.                                           
Starting  >>> catkin_simple                                                    
Starting  >>> nlopt                                                            
Finished  <<< catkin_simple                                [ 0.1 seconds ]     
Starting  >>> eigen_catkin                                                     
Starting  >>> glog_catkin                                                      
Finished  <<< nlopt                                        [ 0.1 seconds ]     
_______________________________________________________________________________
Errors     << glog_catkin:make /home/mbaldwin/logs/glog_catkin/build.make.008.log
CMake Error at glog_src-stamp/download-glog_src.cmake:21 (message):
  error: downloading 'https://github.com/google/glog/archive/v0.3.5.zip'
  failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  

make[2]: *** [glog_src-prefix/src/glog_src-stamp/glog_src-download] Error 1
make[1]: *** [CMakeFiles/glog_src.dir/all] Error 2
make: *** [all] Error 2
cd /home/mbaldwin/catkin_ws/build/glog_catkin; catkin build --get-env glog_catkin | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << glog_catkin:make                             [ Exited with code 2 ]
Failed    <<< glog_catkin                                  [ 0.1 seconds ]     
Abandoned <<< eigen_checks                                 [ Unrelated job failed ]
Abandoned <<< mav_visualization                            [ Unrelated job failed ]
Abandoned <<< mav_trajectory_generation                    [ Unrelated job failed ]
Abandoned <<< mav_trajectory_generation_ros                [ Unrelated job failed ]
Finished  <<< eigen_catkin                                 [ 0.1 seconds ]     
[build] Summary: 3 of 8 packages succeeded.                                    
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: 4 packages were abandoned.                                
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 0.3 seconds total.

I have reinstalled and checked that curl does support https, and that it is pointing to the correct installation on my machine. Any ideas why this might be failing?

**Comment by a-l-a-n** [comment]
Ｉ meet the same problem,how to solve?

**Comment by kylelindgren** [comment]
Gotta install the [glog catkin](https://github.com/ethz-asl/glog_catkin) project
