### ISSUE TITLE
API to provide full-orientation constraints

### ISSUE THREAD

**Issue by chhtz** [ethz-asl/mav_trajectory_generation#89]
Unless I missed something, at the moment waypoints can only feature a position or a a position and a yaw angle, while internally they are stored as full orientation using quaternions.
It would be nice if it was possible to provide that as well using `addConstraint`

**Comment by rikba** [comment]
Thanks for using the library. This library only supports planning in the flat space representation, i.e., [x, y, z, yaw] and it's derivatives. The full state is then derived using the flat state property of the MAV model.

See also
https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=5980409
and https://github.com/ethz-asl/mav_comm/blob/master/mav_msgs/include/mav_msgs/conversions.h#L237-L308

Hope that answers your question.

**Comment by chhtz** [comment]
Thanks for the response! Seems I was not clearly understanding at what point the conversion between XYZ-yaw and full-state was happening.
I guess adding that feature into this library is a bit complicated for a feature-request (if you agree, feel free to close this). 

I will think about how I can solve the underlying problem (I might even need more selective constraints in the future).
