### ISSUE TITLE
Individual MaximumMagnitudeConstraint per segment

### ISSUE THREAD

**Issue by chhtz** [ethz-asl/mav_trajectory_generation#93]
Is it possible to give individual `v_max` constraints per segment? I only found the `addMaximumMagnitudeConstraint` method,  which sets a global constraint.

**Comment by rikba** [comment]
Hi @chhtz 

I think currently it's only possible to give one set of constraints per trajectory. You'd have to define an optimization problem for each trajectory with different constaints and [concatenate](https://github.com/ethz-asl/mav_trajectory_generation/blob/master/mav_trajectory_generation/include/mav_trajectory_generation/trajectory.h#L92-L94) these afterwards..

**Comment by chhtz** [comment]
Thanks for the response. Not sure, how I would get smooth transitions between the sub-trajectories with your suggestion.

What I'm doing at the moment is manually calculating the segment-times (using `computeTimeVelocityRamp`) and just do a linear optimization based on that. I'm sure, I'll overshoot near the transition points, but for now this is sufficient for me.
