### ISSUE TITLE
Adding angular constraints

### ISSUE THREAD

**Issue by viswanarayanans** [ethz-asl/mav_trajectory_generation#98]
I'm using trajectory planner with obstacle avoidance. I have a front facing camera with my drone. So, I want the direction of the drone to be aligned with the direction of trajectory. How can I add the constraints to that?

**Comment by rikba** [comment]
There is no easy way to enforce yaw along the trajectory, except for enforcing yaw at the vertices. However, you can overwrite the yaw policy when you sample the trajectory and send it to your controller. See [mav_voxblox_planning](https://github.com/ethz-asl/mav_voxblox_planning/blob/dc4c653934826999442babc3754383626620cc51/mav_planning_common/src/yaw_policy.cpp#L28-L174) for inspiration.
